---

# It is assumed during the initial provisioning of the server, a LVM physical
# volume and a LVM volume group were created. This file only handles the creation
# of LVM logical volumes in which to run the tomcat container webapps

- name: Create Logical Volumes for webapps
  lvol:
    vg: "{{ vg_name }}"
    lv: "lv_{{ item.app_name }}"
    size: "{{ lv_size }}"
  with_items: "{{ tomcat_applications }}"

- name: Create filesystem on the logical volumes
  filesystem:
    fstype: "{{ lvm_filesystem_type }}"
    dev: "{{ lvm_base_path }}/lv_{{ item.app_name }}"
  with_items: "{{ tomcat_applications }}"

- name: Update fstab and mount the filesystem
  mount:
    path: "/usr/local/{{ item.app_name }}"
    src: "{{ lvm_base_path }}/lv_{{ item.app_name }}"
    fstype: "{{ lvm_filesystem_type }}"
    opts: "defaults"
    dump: "1"
    passno: "2"
    state: "mounted"
  with_items: "{{ tomcat_applications }}"
